fix(gradle): revert Kotlin update to fix tornadofx ClassCastException
The update to 1.4 incurred the following error when starting a game:
java.lang.ClassCastException: class tornadofx.BindingAwareSimpleStringProperty cannot be cast to class javafx.beans.property.ObjectProperty (tornadofx.BindingAwareSimpleStringProperty is in unnamed module of loader 'app'; javafx.beans.property.ObjectProperty is in module javafx.base of loader 'app')
	at sc.gui.model.TeamSettingsModel.<init>(GameCreationModel.kt:48)
	at sc.gui.controller.GameCreationController.<init>(GameCreationController.kt:16)